from django.urls import path
from .views import (
    MovieListView,
    MovieDetailView,
    MovieCreateView,
    MovieUpdateView,
    MovieDeleteView,
    DirectorListView,
    DirectorDetailView,
    DirectorCreateView,
    DirectorUpdateView,
    DirectorDeleteView,
    ActorListView,
    ActorDetailView,
    ActorCreateView,
    ActorUpdateView,
    ActorDeleteView,
)

urlpatterns = [
    path("movies/", MovieListView.as_view(), name="movies"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie"),
    path("movies/new/", MovieCreateView.as_view(), name="movie_create"),
    path("movies/<int:pk>/update/", MovieUpdateView.as_view(), name="movie_update"),
    path("movies/<int:pk>/delete/", MovieDeleteView.as_view(), name="movie_delete"),
    path("directors/", DirectorListView.as_view(), name="directors"),
    path("directors/<int:pk>/", DirectorDetailView.as_view(), name="director"),
    path("directors/new/", DirectorCreateView.as_view(), name="director_create"),
    path("directors/<int:pk>/update/", DirectorUpdateView.as_view(), name="director_update"),
    path("directors/<int:pk>/delete/", DirectorDeleteView.as_view(), name="director_delete"),
    path("actors/", ActorListView.as_view(), name="actors"),
    path("actors/<int:pk>/", ActorDetailView.as_view(), name="actor"),
    path("actors/new/", ActorCreateView.as_view(), name="actor_create"),
    path("actors/<int:pk>/update/", ActorUpdateView.as_view(), name="actor_update"),
    path("actors/<int:pk>/delete/", ActorDeleteView.as_view(), name="actor_delete"),
]