# Generated by Django 4.2.11 on 2024-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("duration", models.IntegerField()),
                ("image", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("year", models.IntegerField()),
            ],
        ),
    ]
